name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests
        
      - name: Debug Build Artifacts
        run: ls -la target/

      - name: Upload JAR as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: spring-boot-app
          path: target/*.jar

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download JAR Artifact
        uses: actions/download-artifact@v3
        with:
          name: spring-boot-app
          path: target/

      - name: Debug Downloaded Artifacts
        run: ls -la target/

      - name: Build Docker Image
        run: docker build -t nikhil0708/ci-cd-demo:latest .

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: docker push nikhil0708/ci-cd-demo:latest
